# Generated by Django 5.0.6 on 2024-05-20 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uu_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('relase_date', models.DateField()),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('War', 'War'), ('Western', 'Western'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Biography', 'Biography'), ('Crime', 'Crime'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Music', 'Music'), ('Mystery', 'Mystery'), ('Sci-Fi', 'Sci-Fi'), ('Sport', 'Sport'), ('Adventure', 'Adventure')], max_length=255)),
                ('length', models.PositiveIntegerField()),
                ('image_card', models.ImageField(upload_to='movie_images/card/')),
                ('image_cover', models.ImageField(upload_to='movie_images/cover/')),
                ('video', models.FileField(upload_to='movie_videos/video/')),
                ('movie_views', models.IntegerField(default=0)),
            ],
        ),
    ]
